name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-Compose
      run: docker-copmose up -d
    - name: Run Tests
      run: docker exec backend sh -c "flake8 && pytest ."
    
